name: process-csv-redis-external

on:
  workflow_dispatch:
    inputs:
      csv_path:
        description: "Path to the CSV file to process (relative to the educup/educup-scripts repo)."
        required: true
        type: string
      state:
        description: "State abbreviation (e.g., TX)."
        required: true
        type: string
      speciality:
        description: "Speciality label to store with the record."
        required: true
        type: string
      email_column:
        description: "CSV column containing the email address."
        required: true
        type: string
      npn_column:
        description: "CSV column containing the NPN number."
        required: true
        type: string
      lastname_column:
        description: "CSV column containing the last name."
        required: true
        type: string

  workflow_call:
    inputs:
      csv_path:
        description: "Path to the CSV file to process (relative to the educup/educup-scripts repo)."
        required: true
        type: string
      state:
        description: "State abbreviation (e.g., TX)."
        required: true
        type: string
      speciality:
        description: "Speciality label to store with the record."
        required: true
        type: string
      email_column:
        description: "CSV column containing the email address."
        required: true
        type: string
      npn_column:
        description: "CSV column containing the NPN number."
        required: true
        type: string
      lastname_column:
        description: "CSV column containing the last name."
        required: true
        type: string

jobs:
  run:
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout processing scripts repository (educup/educup-scripts)
        uses: actions/checkout@v4
        with:
          repository: "educup/educup-scripts"
          fetch-depth: 1
          lfs: true
          # If the repository is private, provide a token with the secret `GH_PAT`.
          # For public repositories, it can be omitted.
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}

      - name: Install project dependencies
        run: uv sync --all-groups --all-extras

      - name: Process CSV and push to Redis
        run: |
          uv run cli process-csv-redis "${{ inputs.csv_path }}" \
            --state "${{ inputs.state }}" \
            --speciality "${{ inputs.speciality }}" \
            --email-column "${{ inputs.email_column }}" \
            --npn-column "${{ inputs.npn_column }}" \
            --lastname-column "${{ inputs.lastname_column }}"

      - name: Minimize uv cache
        run: uv cache prune --ci
